name: tintin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  faker: ^2.2.0
  provider: ^6.1.2
  sqflite: ^2.4.0
  flutter_map: ^7.0.2
  sqflite_common_ffi: ^2.3.4
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.0
  build_runner: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - data/albums.json
